[project]
name = 'link-conc'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Secure-Voting]
path = 'contracts/Secure-Voting.clar'
[contracts.voter-registration]
path = 'contracts/voter-registration.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
