[project]
name = 'link-conc'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.Secure-Voting]
path = 'contracts/Secure-Voting.clar'
clarity_version = 1
epoch = 2.05

[contracts.Vote-validation]
path = 'contracts/Vote-validation.clar'
clarity_version = 3
epoch = 3.0

[contracts.election-contract]
path = 'contracts/election-contract.clar'
clarity_version = 3
epoch = 3.0

[contracts.election-manager]
path = 'contracts/election-manager.clar'
clarity_version = 3
epoch = 3.0

[contracts.vote-tallying]
path = 'contracts/vote-tallying.clar'
clarity_version = 3
epoch = 3.0

[contracts.voter-registration]
path = 'contracts/voter-registration.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
